import { createSlice } from "@reduxjs/toolkit";

// Creating a Redux slice for managing authentication state
const authSlice = createSlice({
  name: "auth",
  initialState: {
    // Initial state for authentication
    token: null,
    isAuthenticated: false,
  },
  reducers: {
    // Action to set authentication token and update isAuthenticated status
    setToken: (state, action) => {
      state.token = action.payload;
      state.isAuthenticated = true;
      console.log("Token set:", action.payload);
    },
    // Action to clear authentication token and update isAuthenticated status
    clearToken: (state) => {
      state.token = null;
      state.isAuthenticated = false;
      console.log("Token cleared");
    },
  },
});

// Exporting actions for use in components and selectors for accessing authentication state
export const { setToken, clearToken } = authSlice.actions;

// Exporting selectors for accessing token and isAuthenticated status
export const selectToken = (state) => state.auth.token;
export const selectIsAuthenticated = (state) => state.auth.isAuthenticated;

// Exporting the reducer function generated by createSlice
export default authSlice.reducer;
