import { createSlice } from "@reduxjs/toolkit";

// Creating a Redux slice for managing user profile information
const userSlice = createSlice({
  name: "user",
  initialState: {
    // Initial state for user profile information
    email: "",
    firstName: "",
    lastName: "",
    createdAt: "",
    updatedAt: "",
    id: "",
  },
  reducers: {
    // Action to set user profile information
    setUserProfile: (state, action) => {
      return {
        ...state,
        ...action.payload,
      };
    },
    // Action to update user profile information
    updateUserProfile: (state, action) => {
      return {
        ...state,
        ...action.payload,
      };
    },
    // Action to clear user profile information
    clearUserProfile: () => {
      return {
        email: "",
        firstName: "",
        lastName: "",
        createdAt: "",
        updatedAt: "",
        id: "",
      };
    },
  },
});

// Exporting actions for use in components and selectors for accessing the user profile state
export const { setUserProfile, updateUserProfile, clearUserProfile } =
  userSlice.actions;

// Exporting the selector for accessing the user profile state
export const selectUserProfile = (state) => state.user;

// Exporting the reducer function generated by createSlice
export default userSlice.reducer;
